### ISSUE TITLE
The script give me 0/10. Is that normal ?

### ISSUE THREAD

**Issue by Kirachiyuki38** [Nv3l/GlobalExamSolver#2]
Is it possible to have only 10/10 on the questions ?

**Comment by Nv3l** [comment]
Hello @Kirachiyuki38.

Short answer : Yes and it does that by default. You have to let the script run a little to see the result.

To be more precise, the script first scrap all good answers. To do that it have to launch the exercise once and respond every question with a dummy answer (the letter "h"). After this, it can acess all answers, and so the script launch the exercise again to solve it to get a 10/10.

NOTE : Only the exercice 1 and 2 are not 10/10 compatible due to check boxes answers.
